title="JP Verb Conjugation"
flavor="A tool to help you REALLY practice verb conjugation."
how_to_use="Enter a verb in the infinitive form and select the tense you want to practice. The tool will show you the conjugation of the verb in the selected tense."