/// Port of the romaji -> hiragana converter in processAnswerKey (drill.js),
/// extended to accept uppercase romaji (Caps Lock friendly): the syllable
/// before the cursor is lowercased before lookup.
(String, int) convertRomajiAtCursor(String value, int cursorPos) {
  if (cursorPos <= 0) return (value, cursorPos);

  final last1 = value.substring(cursorPos - 1, cursorPos).toLowerCase();
  final last2 = cursorPos >= 2
      ? value.substring(cursorPos - 2, cursorPos).toLowerCase()
      : '';
  final last3 = cursorPos >= 3
      ? value.substring(cursorPos - 3, cursorPos).toLowerCase()
      : '';

  String? replacement;
  var consumed = 0;
  if (_replace3.containsKey(last3)) {
    replacement = _replace3[last3];
    consumed = 3;
  } else if (_replace2.containsKey(last2)) {
    replacement = _replace2[last2];
    consumed = 2;
  } else if (_replace1.containsKey(last1)) {
    replacement = _replace1[last1];
    consumed = 1;
  }

  if (replacement == null) return (value, cursorPos);

  // The JS handler slices the tail with (pos, -1), dropping the just-typed
  // trailing character; replicated here.
  final tail = value.substring(
    cursorPos,
    value.length - (value.length > cursorPos ? 1 : 0),
  );
  final newValue =
      value.substring(0, cursorPos - consumed) + replacement + tail;
  return (newValue, cursorPos - consumed + replacement.length);
}

const _replace1 = {'a': 'あ', 'i': 'い', 'u': 'う', 'e': 'え', 'o': 'お'};

// Keep test behavior stable for existing callers.

const _replace2 = {
  'ka': 'か',
  'ki': 'き',
  'ku': 'く',
  'ke': 'け',
  'ko': 'こ',
  'sa': 'さ',
  'si': 'し',
  'su': 'す',
  'se': 'せ',
  'so': 'そ',
  'ta': 'た',
  'ti': 'ち',
  'tu': 'つ',
  'te': 'て',
  'to': 'と',
  'na': 'な',
  'ni': 'に',
  'nu': 'ぬ',
  'ne': 'ね',
  'no': 'の',
  'ha': 'は',
  'hi': 'ひ',
  'hu': 'ふ',
  'he': 'へ',
  'ho': 'ほ',
  'ma': 'ま',
  'mi': 'み',
  'mu': 'む',
  'me': 'め',
  'mo': 'も',
  'ra': 'ら',
  'ri': 'り',
  'ru': 'る',
  're': 'れ',
  'ro': 'ろ',
  'ga': 'が',
  'gi': 'ぎ',
  'gu': 'ぐ',
  'ge': 'げ',
  'go': 'ご',
  'za': 'ざ',
  'zi': 'じ',
  'zu': 'ず',
  'ze': 'ぜ',
  'zo': 'ぞ',
  'da': 'だ',
  'di': 'ぢ',
  'du': 'づ',
  'de': 'で',
  'do': 'ど',
  'ba': 'ば',
  'bi': 'び',
  'bu': 'ぶ',
  'be': 'べ',
  'bo': 'ぼ',
  'pa': 'ぱ',
  'pi': 'ぴ',
  'pu': 'ぷ',
  'pe': 'ぺ',
  'po': 'ぽ',
  'qa': 'くぁ',
  'qi': 'くぃ',
  'qu': 'く',
  'qe': 'くぇ',
  'qo': 'くぉ',
  'wa': 'わ',
  'wi': 'うぃ',
  'wu': 'う',
  'we': 'うぇ',
  'wo': 'を',
  'ya': 'や',
  'yi': 'い',
  'yu': 'ゆ',
  'ye': 'いぇ',
  'yo': 'よ',
  'fa': 'ふぁ',
  'fi': 'ふぃ',
  'fu': 'ふ',
  'fe': 'ふぇ',
  'fo': 'ふぉ',
  'ja': 'じゃ',
  'ji': 'じ',
  'ju': 'じゅ',
  'je': 'じぇ',
  'jo': 'じょ',
  'la': 'ぁ',
  'li': 'ぃ',
  'lu': 'ぅ',
  'le': 'ぇ',
  'lo': 'ぉ',
  'xa': 'ぁ',
  'xi': 'ぃ',
  'xu': 'ぅ',
  'xe': 'ぇ',
  'xo': 'ぉ',
  'ca': 'か',
  'ci': 'し',
  'cu': 'く',
  'ce': 'せ',
  'co': 'こ',
  'va': 'ヴぁ',
  'vi': 'ヴぃ',
  'vu': 'ヴ',
  've': 'ヴぇ',
  'vo': 'ヴぉ',
  'nn': 'ん',
  "n'": 'ん',
  'nb': 'んb',
  'nc': 'んc',
  'nd': 'んd',
  'nf': 'んf',
  'ng': 'んg',
  'nh': 'んh',
  'nj': 'んj',
  'nk': 'んk',
  'nl': 'んl',
  'nm': 'んm',
  'np': 'んp',
  'nq': 'んq',
  'nr': 'んr',
  'ns': 'んs',
  'nt': 'んt',
  'nv': 'んv',
  'nw': 'んw',
  'nx': 'んx',
  'nz': 'んz',
  'aa': 'っa',
  'bb': 'っb',
  'cc': 'っc',
  'dd': 'っd',
  'ee': 'っe',
  'ff': 'っf',
  'gg': 'っg',
  'hh': 'っh',
  'ii': 'っi',
  'jj': 'っj',
  'kk': 'っk',
  'll': 'っl',
  'mm': 'っm',
  'oo': 'っo',
  'pp': 'っp',
  'qq': 'っq',
  'rr': 'っr',
  'ss': 'っs',
  'tt': 'っt',
  'uu': 'っu',
  'vv': 'っv',
  'ww': 'っw',
  'xx': 'っx',
  'yy': 'っy',
  'zz': 'っz',
};

const _replace3 = {
  'kya': 'きゃ',
  'kyi': 'きぃ',
  'kyu': 'きゅ',
  'kye': 'きぇ',
  'kyo': 'きょ',
  'sha': 'しゃ',
  'shi': 'し',
  'shu': 'しゅ',
  'she': 'しぇ',
  'sho': 'しょ',
  'cha': 'ちゃ',
  'chi': 'ち',
  'chu': 'ちゅ',
  'che': 'ちぇ',
  'cho': 'ちょ',
  'nya': 'にゃ',
  'nyi': 'にぃ',
  'nyu': 'にゅ',
  'nye': 'にぇ',
  'nyo': 'にょ',
  'hya': 'ひゃ',
  'hyi': 'ひぃ',
  'hyu': 'ひゅ',
  'hye': 'ひぇ',
  'hyo': 'ひょ',
  'mya': 'みゃ',
  'myi': 'みぃ',
  'myu': 'みゅ',
  'mye': 'みぇ',
  'myo': 'みょ',
  'rya': 'りゃ',
  'ryi': 'りぃ',
  'ryu': 'りゅ',
  'rye': 'りぇ',
  'ryo': 'りょ',
  'gya': 'ぎゃ',
  'gyi': 'ぎぃ',
  'gyu': 'ぎゅ',
  'gye': 'ぎぇ',
  'gyo': 'ぎょ',
  'zya': 'じゃ',
  'zyi': 'じぃ',
  'zyu': 'じゅ',
  'zye': 'じぇ',
  'zyo': 'じょ',
  'dya': 'ぢゃ',
  'dyi': 'ぢぃ',
  'dyu': 'ぢゅ',
  'dye': 'ぢぇ',
  'dyo': 'ぢょ',
  'bya': 'びゃ',
  'byi': 'びぃ',
  'byu': 'びゅ',
  'bye': 'びぇ',
  'byo': 'びょ',
  'pya': 'ぱゃ',
  'pyi': 'ぴぃ',
  'pyu': 'ぴゅ',
  'pye': 'ぴぇ',
  'pyo': 'ぴょ',
  'jiu': 'じゅう',
  'jyu': 'じゅ',
  'jyo': 'じょ',
  'tsu': 'つ',
};
